# Generated by Django 4.2.4 on 2023-12-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
    ]
